USE [master]
GO

/****** Object:  Database [TKB]    Script Date: 4/14/2025 6:24:08 PM ******/
CREATE DATABASE [TKB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TKB', FILENAME = N'L:\SQL\MSSQL16.MSSQLSERVER\MSSQL\DATA\TKB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TKB_log', FILENAME = N'L:\SQL\MSSQL16.MSSQLSERVER\MSSQL\DATA\TKB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TKB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TKB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TKB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TKB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TKB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TKB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TKB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TKB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TKB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TKB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TKB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TKB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TKB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TKB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TKB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TKB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TKB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TKB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TKB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TKB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TKB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TKB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TKB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TKB] SET RECOVERY FULL 
GO

ALTER DATABASE [TKB] SET  MULTI_USER 
GO

ALTER DATABASE [TKB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TKB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TKB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TKB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TKB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TKB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TKB] SET QUERY_STORE = ON
GO

ALTER DATABASE [TKB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TKB] SET  READ_WRITE 
GO


