USE [TKB]
GO

/****** Object:  Table [dbo].[TKB]    Script Date: 4/14/2025 6:25:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TKB](
	[MaTKB] [varchar](10) NOT NULL,
	[MaLHP] [varchar](10) NULL,
	[MaMH] [varchar](10) NULL,
	[PhongHoc] [varchar](10) NULL,
	[Thu] [int] NULL,
	[TietBD] [int] NULL,
	[SoTiet] [int] NULL,
	[GioVao] [time](0) NULL,
	[GioRa] [time](0) NULL,
	[NgayHoc] [date] NULL,
	[MaGV] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaTKB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TKB]  WITH CHECK ADD  CONSTRAINT [FK_TKB_GV1] FOREIGN KEY([MaGV])
REFERENCES [dbo].[GV] ([MaGV])
GO

ALTER TABLE [dbo].[TKB] CHECK CONSTRAINT [FK_TKB_GV1]
GO

ALTER TABLE [dbo].[TKB]  WITH CHECK ADD  CONSTRAINT [FK_TKB_LopHP] FOREIGN KEY([MaLHP])
REFERENCES [dbo].[LopHP] ([MaLHP])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TKB] CHECK CONSTRAINT [FK_TKB_LopHP]
GO

ALTER TABLE [dbo].[TKB]  WITH CHECK ADD  CONSTRAINT [FK_TKB_MonHoc] FOREIGN KEY([MaMH])
REFERENCES [dbo].[MonHoc] ([MaMH])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[TKB] CHECK CONSTRAINT [FK_TKB_MonHoc]
GO


