CREATE DATABASE TKB;
GO
USE TKB;
GO
CREATE TABLE GV (
    MaGV VARCHAR(10) PRIMARY KEY,
    TenGV VARCHAR(20)
);
GO
CREATE TABLE LopHP (
    MaLHP VARCHAR(10) PRIMARY KEY,
    TenLHP VARCHAR(10)
);
GO
CREATE TABLE MonHoc (
    MaMH VARCHAR(10) PRIMARY KEY,
    TenMH VARCHAR(30)
);
GO
CREATE TABLE TKB (
    MaTKB VARCHAR(10) PRIMARY KEY,
    MaLHP VARCHAR(10),
    MaMH VARCHAR(10),
    PhongHoc VARCHAR(10),
    Thu INT,
    TietBD INT,
    SoTiet INT,
    GioVao TIME(0),
    GioRa TIME(0),
    NgayHoc DATE,
    MaGV VARCHAR(10),
    CONSTRAINT FK_TKB_GV FOREIGN KEY (MaGV) REFERENCES GV(MaGV) ON UPDATE CASCADE,
    CONSTRAINT FK_TKB_LopHP FOREIGN KEY (MaLHP) REFERENCES LopHP(MaLHP) ON UPDATE CASCADE,
    CONSTRAINT FK_TKB_MonHoc FOREIGN KEY (MaMH) REFERENCES MonHoc(MaMH) ON UPDATE CASCADE
);
GO